# baseurl: ''
url: "https://tomoe.asia"
title: Tomoe
subtitle:
author: tomoe
simple_search: http://google.com/search
description: A newbie learning to code, who also likes thinking about law / social change / technology
name: tufte
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /posts/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
